# Provenire API
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: provenire_api_development

test:
  <<: *default
  database: provenire_api_test

production:
  url: <%= ENV['DATABASE_URL'] %>
