# Antiquarium API
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: antiquarium_api_development

test:
  <<: *default
  database: antiquarium_api_test

production:
  url: <%= ENV['DATABASE_URL'] %>
